version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./storage/database:/data/db

  mongoku:
    image: huggingface/mongoku
    container_name: mongoku
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - MONGOKU_DEFAULT_CONNECTION_HOST=mongodb://mongo:27017
    depends_on:
      - mongo
