version: '3.8'

services:
  ####################################
  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./storage/database:/data/db

  ####################################
  # Open Policy Agent
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    command: ["run", "--server", "--addr", "0.0.0.0:8181", "/policies"]
    volumes:
      - ./storage/opa:/policies
    ports:
      - "8181:8181"
    restart: unless-stopped

  ####################################
  # SSO Server
  sso-server:
    build:
      context: ./sso
      dockerfile: Dockerfile
    container_name: sso-server
    ports:
      - "5000:5000"
    restart: unless-stopped
